rtsp_url: auto
#rtsp_url: 0
#rtsp_url: video=USB Video Device
#rtsp_url: C:/Users/igors/Videos/WST/WST-graduation-Video-2025-12-31.mp4
#rtsp_url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
#rtsp_url: rtsp://localhost:8554/live
frame_sample_fps: 2
frame_width: 640
frame_height: 360
#camera_name: USB Video Device
#model_name: mobilenet_v3_small
model_name: person_detector
device: cpu
metrics_log_every: 50
save_processed: false
processed_dir: data/processed
class_topk: 5
person_score_threshold: 0.6
log_level: INFO
capture_inference: false
capture_dir: data/inference
capture_every_n: 10
#capture_s3_bucket: your-s3-bucket
capture_s3_prefix: inference